name: Deploying to Staging

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file
        run: |
          echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .env

      # - name: Setup GCP Credentials
      #   run: |
      #     echo '${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}' > $GITHUB_WORKSPACE/key.json
      #     echo "GOOGLE_APPLICATION_CREDENTIALS=$GITHUB_WORKSPACE/key.json" >> $GITHUB_ENV
          
      # - name: Verify GCP Credentials
      #   run: |
      #     echo "Checking if key.json exists..."
      #     ls -l $GITHUB_WORKSPACE/key.json
      #     echo "GOOGLE_APPLICATION_CREDENTIALS is set to: $GOOGLE_APPLICATION_CREDENTIALS"
          
      - name: Run unit tests
        run: pytest --cov=. --cov-config=.coveragerc --cov-report xml
        continue-on-error: false

      # - uses: SonarSource/sonarqube-scan-action@v4
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/navigo-backend:staging

      - name: Releasing New Version
        uses: appleboy/ssh-action@v1.2.0
        with:
          proxy_username: ${{ secrets.SSH_PROXY_USERNAME }}
          proxy_host: ${{ secrets.SSH_PROXY_HOST }}
          proxy_port: ${{ secrets.SSH_PROXY_PORT }}
          proxy_passphrase: ${{ secrets.SSH_PASSPHRASE }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          proxy_key: ${{ secrets.SSH_PROXY_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker rmi $(docker images -a)
            docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/navigo-backend:staging
            echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .env
            docker compose up -d
